language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
#  - "pypy"
# command to install dependencies
virtualenv:
  system_site_packages: true
install:
#  - pip install .
#
# - pip install -r requirements.txt
- sudo add-apt-repository ppa:sonkun/sfml-stable -y
- sudo apt-get update -qq
- sudo apt-get install python-sfml -y
#before_script:

# command to run tests
script: python -m test.test_all_of_the_units